name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy to Cloudflare Pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to Cloudflare Pages
        run: node scripts/deploy-cloudflare-pages.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: Add deployment comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const deploymentUrl = `https://courses-careers-com.pages.dev`;
            const previewUrl = `https://${context.payload.pull_request.number}.courses-careers-com.pages.dev`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Cloudflare Pages Deployment
              
              ✅ **Deployment successful!**
              
              - **Production URL**: ${deploymentUrl}
              - **Preview URL**: ${previewUrl}
              
              Preview deployments are available for all pull requests.`
            });

  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check || echo "Type check skipped"

      - name: Lint check
        run: npm run lint:check || echo "Lint check skipped"

      - name: Build test
        run: npm run build